name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex

    strategy:
      matrix:
        repo:
          - owner: OWNER_MATTHEW
            name: REPO_MATTHEW
            token: TOKEN_MATTHEW
            email: EMAIL_MATTHEW
          - owner: OWNER_RYU_HYEJIN
            name: REPO_RYU_HYEJIN
            token: TOKEN_RYU_HYEJIN
            email: EMAIL_RYU_HYEJIN
          - owner: OWNER_SANG_3
            name: REPO_SANG_3
            token: TOKEN_SANG_3
            email: EMAIL_SANG_3
          - owner: OWNER_HS_PARK
            name: REPO_HS_PARK
            token: TOKEN_HS_PARK
            email: EMAIL_HS_PARK
          - owner: OWNER_OJA
            name: REPO_OJA
            token: TOKEN_OJA
            email: EMAIL_OJA

    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets[matrix.repo.token] }}
        with:
          source-directory: "output"
          destination-github-username: ${{ matrix.repo.owner }}
          destination-repository-name: ${{ matrix.repo.name }}
          user-email: ${{ secrets[matrix.repo.email] }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
